site_name: "FRAM - NVE's Open-Source Power Market Modelling Framework"
site_url: https://nve.github.io/fram/
site_description: "FRAM is NVE's open-source framework for building, running, and comparing power-market models."

theme:
  features:
    - navigation.sections
    - content.code.copy
  name: "material"
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
- attr_list
- tables

plugins:
  - mike
  - search
  - macros
  - table-reader

nav:
  - index.md
  - Getting Started: 
    - installation_and_demo.md
  - Understanding FRAM:
    - how_fram_works.md
    - why_core_model.md
    - why_components.md
    - what_special_jules.md
  - Background:
    - why_we_developed.md
    - why_is_it_called.md
  - How-to Guides:
    - how_to_add_model.md
  - Contact:
    - how_to_contact.md

extra:
  version:
    provider: mike
  juleslinks:
      jules:  https://github.com/NVE/JulES/
  framlinks:
    demo:     https://github.com/NVE/fram-demo
    video:    https://www.youtube.com/watch?v=YmQZLke86vY
    core:     https://nve.github.io/fram-core/
    data:     https://nve.github.io/fram-data/
    julesAPI: https://nve.github.io/fram-jules/
    dataset:  https://doi.org/10.5281/zenodo.17294466
    demodocs: https://nve.github.io/fram-demo/latest/


extra_css:
  - assets/styles.css